import "./css/styles.scss"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div data-testid="main">
        {children}
      </div>
      </body>
    </html>
  );
}
